// src/routes/index.ts
import express from "express";
import continentRoutes from "./continents";
import countryRoutes from "./country";
import cityRoutes from "./city";
import activityRoutes from "./activity";
import bookingRoutes from "./Booking";
import holidayPackageRoutes from "./holidayPackage";
import activityDetailRoutes from "./ActivityDetail";
import cartRoutes from "./Cart";
import enquiryRoutes from "./Enquiry";
import globalRoutes from "./global";
import dealRoute from "./deal";
import contactRoute from "./Contact";
import AdminRoutes from "./Admin";
import vehicleRoutes from "./vehicle";
import dashboardRoutes from "./dashboard";
import hotelRoutes from "./hotel";
import supplierRoutes from "./supplier";
import customerRoutes from "./customer";
const router = express.Router();

router.use("/continents", continentRoutes);
router.use("/countries", countryRoutes);
router.use("/cities", cityRoutes);
router.use("/activities", activityRoutes);
router.use("/bookings", bookingRoutes);
router.use("/holidayPackages",holidayPackageRoutes );
router.use("/activityDetail",activityDetailRoutes );
router.use("/cart",cartRoutes);
router.use("/book",bookingRoutes );
router.use("/enquiry", enquiryRoutes);
router.use("/global-search", globalRoutes);
router.use("/deal", dealRoute);
router.use("/contact", contactRoute); 
router.use("/vehicle", vehicleRoutes);
router.use("/admin", AdminRoutes); 
router.use("/dashboard", dashboardRoutes); 
router.use("/hotel", hotelRoutes); 
router.use("/supplier", supplierRoutes);
router.use("/customer", customerRoutes);
export default router;
